servers:
- name: Django + Graphene v3
  path: servers/django-graphene/

- name: Django + Strawberry
  path: servers/django-strawberry/

- name: Django + Strawberry (raw queryset)
  path: servers/django-strawberry-queryset/

# - name: Django + Graphql Core v3
#   path: servers/django-graphql-core/

- name: Django Rest Framework
  path: servers/django-rest-framework/

- name: Django Plain JSON
  path: servers/django-plain-json/

# - name: Starlette + Graphene v3
#   path: servers/starlette-graphene/

# - name: Starlette + Strawberry
#   path: servers/starlette-strawberry/

# - name: Starlette + Graphql Core v3
#   path: servers/starlette-graphql-core/

# - name: Starlette Plain JSON 
#   path: servers/starlette-plain-json/

queries:
- name: Top 250 rated movies
  runner: queries/top-movies.js
  server_overrides:
    - name: Django Rest Framework
      runner: queries/top-movies-rest.js
    - name: Django Plain JSON
      runner: queries/top-movies-rest.js
