servers:
- name: Django + Graphene v3
  path: servers/django-graphene/

- name: Django + Strawberry 
  path: servers/django-strawberry/

- name: Django Rest Framework
  path: servers/django-rest-framework/

- name: Django + Graphql Core v3
  path: servers/django-graphql-core/

- name: Django Plain JSON
  path: servers/django-plain-json/

- name: Starlette + Graphene v3
  path: servers/starlette-graphene/

- name: Starlette + Strawberry
  path: servers/starlette-strawberry/

- name: Starlette + Graphql Core v3
  path: servers/starlette-graphql-core/

- name: Starlette Plain JSON 
  path: servers/starlette-plain-json/

queries:
- name: Top 250 rated movies
  runner: queries/top-movies.js

# - name: Basic
#   runner: queries/basic.js
#   filename: queries/basic.graphql
#   expectedResultFilename: queries/basic.json

# - name: Object List
#   runner: queries/object_list.js
#   filename: queries/object_list.graphql
#   expectedResultFilename: queries/object_list.json

# - name: Scalar List
#   runner: queries/scalar_list.js
#   filename: queries/scalar_list.graphql
#   expectedResultFilename: queries/scalar_list.json

# - name: Introspection
#   filename: queries/introspection.graphql
#   expectedResultFilename: queries/scalar_list.json
