servers:

- name: Django + Graphene v2
  endpoint: http://localhost:8001/graphql/
  run:
    command: venv/bin/uvicorn app.asgi:application --port 8001 --workers=4 --log-level error
    cwd: servers/django-graphene/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Django + Strawberry 
  endpoint: http://localhost:8002/graphql/
  run:
    command: venv/bin/uvicorn app.asgi:application --port 8002 --workers=4 --log-level error
    cwd: servers/django-strawberry/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Django + Ariadne
  endpoint: http://localhost:8005/graphql/
  run:
    command: venv/bin/uvicorn app.asgi:application --port 8005 --workers=4 --log-level error
    cwd: servers/django-ariadne/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Starlette + Graphene v3 alpha
  endpoint: http://localhost:8003/graphql/
  run:
    command: venv/bin/uvicorn server:app --port 8003 --workers=4 --log-level error
    cwd: servers/starlette-graphene-v3/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Starlette + Strawberry
  endpoint: http://localhost:8004/graphql/
  run:
    command: venv/bin/uvicorn server:app --port 8004 --workers=4 --log-level error
    cwd: servers/starlette-strawberry/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Starlette + Ariadne 
  endpoint: http://localhost:8006/graphql/
  run:
    command: venv/bin/uvicorn server:app --port 8006 --workers=4 --log-level error
    cwd: servers/starlette-ariadne/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Strawberry (ASGI)
  endpoint: http://localhost:8007/graphql/
  run:
    command: venv/bin/uvicorn server:app --port 8007 --workers=4 --log-level error
    cwd: servers/asgi-strawberry/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

- name: Ariadne (ASGI)
  endpoint: http://localhost:8008/graphql/
  run:
    command: venv/bin/uvicorn server:app --port 8008 --workers=4 --log-level error
    cwd: servers/asgi-ariadne/
    startupTime: 2s
  warmup:
    concurrency: 1
    duration: 5s

# - name: Express GraphQL 
#   endpoint: http://localhost:4000/graphql
#   run:
#     command: node app.js
#     cwd: servers/node-express/
#     startupTime: 2s
#   warmup:
#     concurrency: 1
#     duration: 5s

queries:
- name: Basic
  filename: queries/basic.graphql
  expectedResultFilename: queries/basic.json

- name: Object List
  filename: queries/object_list.graphql
  expectedResultFilename: queries/object_list.json

- name: Scalar List
  filename: queries/scalar_list.graphql
  expectedResultFilename: queries/scalar_list.json

# - name: Introspection
#   filename: queries/introspection.graphql
#   expectedResultFilename: queries/scalar_list.json
